image: hub.docker.rpm.hicare.net/napi-builder

clone:
    depth: full

definitions:
    caches:
        pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store
        node: node_modules
    steps:
        - step: &napi_build

pipelines:
    branches:
        none:
            - step:
                  name: branch
                  script:
                      - echo 'branch section'