[package]
edition = "2021"
name = "hicare-napi_backend_napi"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "3.0.0-alpha.3", default-features = false, features = ["napi9", "serde", "serde-json", "object_indexmap", "async", "tokio_rt", "tokio_fs", "tokio_io_util", "tokio_macros"] }
tokio = { version = "1.38.0", default-features = false, features = ["rt", "time"] }
indexmap = { version = "2.2.6" }
napi-derive = { version = "3.0.0-alpha.2", default-features = false, features = ["type-def"] }

# pbkdf2
pbkdf2 = { version = "0.13.0-pre.0", features = ["sha1", "simple"] }
sha1 = { version = "0.11.0-pre.3" }
# pbkdf2

# aes256cbc
cbc = { version = "0.1.2", features = ["block-padding"] }
aes = { version = "0.8.4" }
md5 = { version = "0.7.0" }
block-padding = { version = "0.3.3" }
# aes256cbc

#base64
base64-simd = { version = "0.8.0", features = ["detect", "alloc"], default-features = false }
#base64

#uuid
uuid = { version = "1.9.1", default-features = false ,features = ["v4", "fast-rng"]}
uuid-simd = { version = "0.8.0" }
nanoid = { version = "0.4.0" }
#uuid

#json
serde = { version = "1.0.203", features = ['derive'] }
serde_json = { version = "1.0.117" }
once_cell = "1.19.0"
#json

#jsonwebtoken
jsonwebtoken = { version = "9.3.0" }
#jsonwebtoken

mimalloc = { version = "0.1.43", features = ["override"] }
parking_lot = { version = "0.12.3" }
lazy_static = { version = "1.5.0" }
crossbeam-queue = { version = "0.3.11" }
scopeguard = { version = "1.2.0" }

[build-dependencies]
napi-build = { version = "2.1.3" }

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
strip = "symbols"
