/* auto-generated by NAPI-RS */
/* eslint-disable */
export function decryptAES(symKey: string, text: string): string

export function encryptAES(symKey: string, text: string): string

export function fromBase64(input: string): string

export interface KdfOption {
  iterations?: number
  keySize?: number
}

export function parse(jsonString: string): any

export function PBKDF2(password: string, salt: string, cfg?: KdfOption | undefined | null): string

export function stringify(value: any): string

export function stringifyPretty(value: any): string

export function toBase64(input: string): string

